-- Intentionally empty. This migration exists only to carry the snapshot
-- (meta/0005_snapshot.json) that first describes `articles.content_tsv` and
-- its GIN index, which db/schema.ts now declares via a `tsvector` customType.
--
-- Both objects are already created by 0001_fts_index.sql, so there is nothing
-- left to apply: re-issuing the DDL here would either fail on an existing
-- database or, with IF NOT EXISTS guards, emit "already exists, skipping"
-- NOTICEs on every fresh migrate. Neither is worth it for zero effect.
--
-- The snapshot is the point: from here on `pnpm db:generate` diffs against a
-- picture of the database that includes content_tsv, so schema changes to it
-- are generated like any other column.
